name = "ImplicitArrays"
uuid = "2c62951c-9479-4435-88c8-614a84373d38"
desc = "Implicit Arrays for Julia"
authors = ["Thomas Kemmer <thomas@binaryden.de>"]
version = "0.2.1"

[compat]
Aqua = "0.8"
TestItemRunner = "0.2, 1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Aqua", "Test", "TestItemRunner"]
