name = "ImplicitArrays"
uuid = "2c62951c-9479-4435-88c8-614a84373d38"
desc = "Implicit Arrays for Julia"
version = "0.3.0"
authors = ["Thomas Kemmer <thomas@binaryden.de>"]

[compat]
Aqua = "0.8.14"
ParallelTestRunner = "2.0.1"
Test = "1.10"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ParallelTestRunner = "d3525ed8-44d0-4b2c-a655-542cee43accc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "ParallelTestRunner", "Test"]
