name = "ImplicitArrays"
uuid = "2c62951c-9479-4435-88c8-614a84373d38"
desc = "Implicit Arrays for Julia"
authors = ["Thomas Kemmer <thomas@binaryden.de>"]
version = "0.2.1"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
